name: cube
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - expat=2.6.2
  - fonttools=4.51.0
  - freetype=2.12.1
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.0.14
  - packaging=24.1
  - pandas=2.2.2
  - patsy=0.5.6
  - pillow=10.4.0
  - pip=24.2
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=5
  - pyparsing=3.1.2
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - scikit-posthocs=0.9.0
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - tzdata=2024a
  - unicodedata2=15.1.0
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - anyio==4.4.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.8.30
      - cffi==1.17.0
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - debugpy==1.8.5
      - defusedxml==0.7.1
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - idna==3.8
      - ipykernel==6.29.5
      - ipython==8.27.0
      - isoduration==20.11.0
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - python-json-logger==2.0.7
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.3.0
      - types-python-dateutil==2.9.0.20240821
      - uri-template==1.3.0
      - urllib3==2.2.2
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
